# Defines a small topology of 3 routers, 5 networks and 2 endpoints
# docker compose -f compose.yaml --profile routers up -d
# docker compose -f compose.yaml --profile endpoints --profile routers up -d
# docker compose -f compose.yaml --profile routers --profile endpoints down -t 1
services:

  tcpdump:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pcap:/pcap
    networks:
      stub1:
      stub2:
      stub3:
      stub4:
      trans1:
      trans2:
      trans3:
    privileged: true
    command: tcpdump -i any -w /pcap/capture.pcap

  # 5 routers connecting networks
  router1:
    profiles: ["routers"]
    image: "pycimage"
    build: .
    volumes:
      - .:/compnets
    command: python3 /compnets/server.py router1
    stdin_open: true
    tty: true
    environment:
      HOSTNAME: router1
    networks:
      - stub1
      - trans1

  router2:
    profiles: ["routers"]
    image: "pycimage"
    build: .
    volumes:
      - .:/compnets
    command: python3 /compnets/server.py router2
    stdin_open: true
    tty: true
    environment:
      HOSTNAME: router2
    networks:
      - trans1
      - trans2
      - stub3

  router3:
    profiles: ["routers"]
    image: "pycimage"
    build: .
    volumes:
      - .:/compnets
    command: python3 /compnets/server.py router3
    stdin_open: true
    tty: true
    environment:
      HOSTNAME: router3
    networks:
      - stub2
      - trans2
      - stub4
      - trans3 

  # 2 endpoints creating traffic
  client1:
    profiles: ["endpoints"]
    image: "pycimage"
    build: .
    volumes:
      - .:/compnets
    command: python3 /compnets/client.py client1
    stdin_open: true
    tty: true
    depends_on:
      - router1
    environment:
      HOSTNAME: client1
    networks:
      - stub1

  client2:
    profiles: ["endpoints"]
    image: "pycimage"
    build: .
    volumes:
      - .:/compnets
    command: python3 /compnets/client.py client2
    stdin_open: true
    tty: true
    depends_on:
      - router3
    environment:
      HOSTNAME: client2
    networks:
      - stub2

  client3:
    profiles: ["endpoints"]
    image: "pycimage"
    build: .
    volumes:
      - .:/compnets
    command: python3 /compnets/client.py client3
    stdin_open: true
    tty: true
    depends_on:
      - router2
    environment:
      HOSTNAME: client3
    networks:
      - stub3
      
  client4:
    profiles: ["endpoints"]
    image: "pycimage"
    build: .
    volumes:
      - .:/compnets
    command: python3 /compnets/client.py client4
    stdin_open: true
    tty: true
    depends_on:
      - router3
    environment:
      HOSTNAME: client4
    networks:
      - stub4


# 4 Stub networks and 3 transient networks
networks:
  stub1:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  stub2:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
  stub3:
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
  stub4:
    ipam:
      driver: default
      config:
        - subnet: 192.168.30.0/24
  trans1:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
  trans2:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
  trans3:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
